spring:
  config:
    activate:
      on-profile: prod
  #    import:
  #      classpath:/application-aws.yml

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  access-header: Authorization
  refresh-header: Refresh
  secret: ${JWT_SECRET}

cloud:
  aws:
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false